import type { Metadata } from "next";
import { Footer } from "@/components/layout/footer";
import { Masthead } from "@/components/layout/masthead";
import { PlaceholderBar } from "@/components/layout/placeholder-bar";
import { Shell } from "@/components/layout/shell";
import { fontVariables } from "./fonts";
import "./globals.css";

// The description is Enzo's own, from section 1 of the foundation doc, trimmed
// to fit a search result rather than rewritten. Nothing here positions the
// publication in words he did not use.
const DESCRIPTION =
  "The intersection of Space, AI, Robotics, and Energy, through the lens of science, economics, politics. These industries are interconnected and affect us all.";

// Icons and the Open Graph image are picked up by file convention from
// app/icon.png, app/icon1.png, app/apple-icon.png, app/favicon.ico, and
// app/opengraph-image.png. All five are generated by npm run icons from the
// monogram and the lockup, so they cannot drift away from the components.
export const metadata: Metadata = {
  metadataBase: new URL("https://burnrate.news"),
  title: {
    default: "Burn Rate",
    template: "%s · Burn Rate",
  },
  description: DESCRIPTION,
  openGraph: {
    type: "website",
    siteName: "Burn Rate",
    title: "Burn Rate",
    description: DESCRIPTION,
    url: "/",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Burn Rate",
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariables}>
      <body>
        <PlaceholderBar />
        <Shell>
          <Masthead />
          {children}
          <Footer />
        </Shell>
      </body>
    </html>
  );
}
